version: "3"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - mysql
        networks:
            - default
    mysql:
        image: mysql:5.7.13
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./dump:/docker-entrypoint-initdb.d/
        ports:
          - "3306:3306" 
        networks:
            - default
          
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - mysql
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
          MYSQL_USER: test
          MYSQL_PASSWORD: 123456
          MYSQL_ROOT_PASSWORD: root
        ports:
          - '8080:80'